### ISSUE TITLE
ac3mode

### ISSUE THREAD

**Issue by timehlers** [vdr-projects/vdr-projects.github.io#1]
Hi,

I am still using the plugin "ac3mode", which you can find here:

http://www.vdr-wiki.de/wiki/index.php/Ac3mode-plugin

In 2012 I have ported it to VDR >= 1.7 (but I am not the original author). My version is still usable in 2.2 and still compiles in in the newest 2.3 version (this is what I have tested, I still use vdr-2.2 here), although it has an "old-fashioned" Makefile. It would be nice, if you could add it to the collection. Making thinks easier for you, I made a git-repo to pull from here:

https://github.com/timehlers/vdr-plugin-ac3mode.git

Thanks

Tim

**Comment by CReimer** [comment]
I'll keep this issue open for now until we've decided on how to handle community updates.

**Comment by M-Reimer** [comment]
Done
