### ISSUE TITLE
vdr-plugin-vnsiserver

### ISSUE THREAD

**Issue by Dis90** [vdr-projects/vdr-projects.github.io#11]
Hi,

Is it possible to make vnsiserver community maintained? Current repository seems to be dead. There's two open PR's (one from me).
https://github.com/mdre77/vdr-plugin-vnsiserver

**Comment by M-Reimer** [comment]
"Community maintained", how I would define it, means "keep it compiling and running with future VDR versions". 
In case of the vnsiserver plugin this is not an issue. It compiles fine without any issues so no pull request for compile fixes needed.

The "community maintained" plugins don't have anyone who decides to be the maintainer. This means that someone of the vdr-projects team (most probably me), has to decide about pull requests. And everything which is not a compile fix will be probably rejected by me as I'm not the "VDR plugin genius" who can decide about all possible plugins which new feature or change would be a good idea and does not break things for other users.

Another issue with vnsiserver is that it has a counterpart on the Kodi side which, currently, is maintained by the Kodi team itself which is only keeping it running without adding features (similar to what "community maintained" means here on the "vdr-projects" GitHub organization).

What the vnsiserver plugin would need for new features is the "one person" which has developed some insight into how the plugin works (so not me) and is willing to be the "new maintainer" for it. If this person is found, I would happily create the repo in context of the "vdr-projects" organization, but give the new maintainer full permissions on his new project so I don't have to take care of it.

That's the first step. After that we have to see how the Kodi addon can receive further updates. The problem with "adopting" the Kodi addon is that Kodi gets regular updates and changes to the PVR interface. So the preferable solution would be to try to create a pull request on its current location to get a new feature in but still get future PVR changes done by the Kodi team itself.

So many questions and small tasks but none of this gets solved by making something as complex as vnsiserver "community maintained". So I'm closing here. If you want to take full maintainership for the nsiserver plugin, then feel free to either host on your own GitHub account or create a new Issue for requesting a vdr-projects repo creation where you will be the maintainer for.

Oh, forgot: It is always a good idea to ask (in an Issue) first if the current maintainer (mdre77) really no longer wants to maintain the plugin.

**Comment by M-Reimer** [comment]
Maybe let's add this final thought: What "mdre77" did was stability fixes. He did not change the interface to Kodi in any way.

So let's assume your Pull Request is accepted (probably by you as the new maintainer). After that you create a Pull request for the Kodi addon and they deny it with the reason "if you want to add features, adopt the addon". Now you immediately have a somewhat larger job to do as now it is your job to keep up with Kodi updates.

**Comment by Dis90** [comment]
Thanks for your reply. Let's first say that I don't want to be maintainer for vnsi. I just wanted to make this new feature and MarkusEh from Kodi forums suggested moving vnsi to vdr-projects (https://forum.kodi.tv/showthread.php?tid=363935&pid=3092569#pid3092569).

On Kodi side of things there's not much changes needed to get this to work (https://github.com/Dis90/pvr.vdr.vnsi/commit/39e0fc535c82ed83b7a3d08385a6cd5e2ca8141d). I probably need to open issue on pvr.vdr.vnsi and ask if new features are even accepted. What you think?

But even if new features are accepted that doesn't change that fact that also vnsiserver need to have version which supports new features and I don't understand vnsi enough to be maintainer. And I also don't have enough time.

> So many questions and small tasks but none of this gets solved by making something as complex as vnsiserver "community maintained". So I'm closing here. 

I understand. Let's hope someone someday wants to continue maintaining vnsi.

**Comment by M-Reimer** [comment]
> Thanks for your reply. Let's first say that I don't want to be maintainer for vnsi.

Me neither.

> I just wanted to make this new feature and MarkusEh from Kodi forums suggested moving vnsi to vdr-projects (https://forum.kodi.tv/showthread.php?tid=363935&pid=3092569#pid3092569).

This may sound good in theory but in fact there is no workflow on what to do with new features on "community maintained" projects.

> On Kodi side of things there's not much changes needed to get this to work ([Dis90/pvr.vdr.vnsi@39e0fc5](https://github.com/Dis90/pvr.vdr.vnsi/commit/39e0fc535c82ed83b7a3d08385a6cd5e2ca8141d)).

That's not my definition of "not much changes" :laughing: 

> I probably need to open issue on pvr.vdr.vnsi and ask if new features are even accepted. What you think?

That could be a first step. And I'm somewhat sure that your "not much changes" will be too much changes for them to actually being able to review without being able to actually test the feature!

> But even if new features are accepted that doesn't change that fact that also vnsiserver need to have version which supports new features and I don't understand vnsi enough to be maintainer. And I also don't have enough time.

So let's spin this further. Let's assume vniserver gets a "community maintained" project which (by current definition) could only happen if it fails to compile as that's the minimum requirement for it to be still usable.

Then it would have a repository in context of vdr-projects where you could point a pull request to. What would you expect to happen next? Who exactly should review your pull request and merge it? The idea of "community maintenance" is not "someone of the vdr-projects organization just accepts all changes coming in without any testing or review".

The currently planned way of handling "feature pull requests" to (currently "community maintained") projects is to just keep it open and hope someone **of the community** (not me, my job ends when the repo is created) steps in and responds in a way like "tested it, works for me". Example can be found here: https://github.com/vdr-projects/vdr-plugin-streamdev/pull/2
The community change is "archived" here for everyone, who is interested, to find. But I won't merge this as I can't test and so can't decide if this is a good change.

**Comment by M-Reimer** [comment]
Let's say a possible workflow for getting features in "community maintained" projects (without anyone stepping in as maintainer) would be the following (in case of vnsi server):

1. Ask the current maintainer if he still plans to update or if his repo should be moved to a community driven GitHub organization
2. Check if you could actually get your change added to the Kodi addon.
3. At that point I could create the repo, you could point your pull request to it.
4. I would probably do some first checks (coding style, indentation) so we don't make a big mess here.
5. I can't test the feature. I won't accept the pull request. So it's your job to get someone from the community (probably from vdr-portal.de) to do the testing and commenting his test results on the pull request
6. If at least two VDR users verify that the change works for them I would accept the pull request

**Comment by Dis90** [comment]
Again huge thanks for your replies. I opened issue https://github.com/kodi-pvr/pvr.vdr.vnsi/issues/179 but I think new features are not accepted.

**Comment by M-Reimer** [comment]
I guess you successfully managed the first obstacle: https://github.com/kodi-pvr/pvr.vdr.vnsi/issues/179#issuecomment-1084588873

So I'll reopen here for now, in case you really want to push on this change.

I have created a request to the current vnsiserver maintainer: https://github.com/mdre77/vdr-plugin-vnsiserver/issues/5

**Comment by M-Reimer** [comment]
I did a search for the thread in VDR-Portal where mdre announced his updates to vnsi, and there he mentioned the following:

https://www.vdr-portal.de/forum/index.php?thread/134021-vdr-plugin-vnsi/&postID=1333547#post1333547
> Die Issues auf github sind erst mal aktiv. Ich kann jedoch nicht versprechen neue Features zu entwickeln. Mein vorrangiges Ziel ist, dass es auch weiterhin funktioniert.

Translated to English this means something like "I can not promise to develop any new features. My primary target is to keep the plugin running".

**Comment by M-Reimer** [comment]
I've created the repo now and tagged a release for the current state of development.

So you can point your Pull Request to this repo, now. But keep in mind that I won't accept it directly as I will not test your changes. Others have to do the testing.

If at least two people tested your changes and validated that they are working, I would accept the pull request to a new branch (for easy revert) and tag a pre release which will get a "real release" once your changes are accepted on the Kodi plugin side.

**Comment by Dis90** [comment]
Thanks. I opened PR and I will make new thread to vdrportal later today. Hopefully we can find users to test these new features.

Edit. thread opened https://www.vdr-portal.de/forum/index.php?thread/135110-artwork-and-backend-resume-support-testers-needed/
