### ISSUE TITLE
vdr-plugin-pvr350

### ISSUE THREAD

**Issue by DrStrangeHH** [vdr-projects/vdr-projects.github.io#15]
I am the last maintainer of this plugin, which creates an output device for the old Hauppauge PVR350 PCI card. It is probably useless nowadays, but can still be used for digitizing VHS tapes in combination withe the pvrinput-Plugin. I updated the pvr350-plugin recently to the current API. In case anybody is still using this, I would like to release it as simple tarball (no git). My idea is to put it into my Dropbox or Google Drive and link on https://vdr-projects.github.io/ to it. Is this possible?

**Comment by M-Reimer** [comment]
I would prefer to have everything archived as complete as possible on a git repo. Best would be if you can push your own changes.

If this is not possible at all it would be OK if you create issues for new versions and I would push the files to a repo.

Please tell me which way you prefer. If previous versions exist, maybe provide a link so I can import the existing history of old versions.

**Comment by M-Reimer** [comment]
I've prepared a new repository: https://github.com/vdr-projects/vdr-plugin-pvr350

Which hosts the existing releases: https://github.com/vdr-projects/vdr-plugin-pvr350/tags

If you like to try using GIT, I can give you commit access directly to this. But you don't have to. Just attach the new version archive to this issue and I'll integrate it for you.

The goal of the whole "vdr-projects thing" was to somewhat archive and preserve plugins. Even if they are no longer relevant or don't build at all. Everything can be valuable even if someone just takes portions from old stuff to create something new from it.

Linking to Dropbox or Google Drive wouldn't really fit into this goal. Both can disappear, again, at any time, just as we saw with projects.vdr-developer.org.

**Comment by DrStrangeHH** [comment]
Thank you, Manuel! Attached is the new version. It is likely that there will come no further versions as development has stopped. My goal was to make the plugin work without using deprecated ioctl from old DVB API, as it is likely that this will be removed from the kernel soon (see current discussion for av7110 Full Feature cards).
I fully agree - everything can be valuable!
I had to create a new zip archiv with the tgz inside, because github did not accept tgz (although it is advertised)
[attachment.zip](https://github.com/vdr-projects/vdr-projects.github.io/files/10527104/attachment.zip)

**Comment by M-Reimer** [comment]
Update is pushed: https://github.com/vdr-projects/vdr-plugin-pvr350/archive/refs/tags/2.0.0.tar.gz

How should I document the maintenance status of this plugin when adding to the list? "Active Maintainer"?

**Comment by DrStrangeHH** [comment]
yes, please. I will try to keep it alive as long as possible.

**Comment by M-Reimer** [comment]
Done. For future updates, just open a new issue here. Maybe also add yourself to the watch list of the  https://github.com/vdr-projects/vdr-plugin-pvr350 repo (Upper right, click "Watch") so you get notified if someone creates an Issue for your plugin.

And about the file extension of new packages: Maybe use ".tar.gz" instead of ".tgz". Yes, ".tgz" is a pretty common shorthand but maybe GitHub doesn't have this shorthand version on its list of allowed file extensions.
