### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by a-mair** [vdr-projects/vdr-projects.github.io#16]
Hi,

as requested, my other projects:
* https://github.com/vdr-projects/vdr-plugin-skinenigmang
* https://github.com/vdr-projects/vdr-plugin-extrecmenu

You can add me as maintainer if you want to.

Regards,
Andreas

**Comment by M-Reimer** [comment]
No problem. I linked "extrecmenu" to the new "extrecmenung" but I can remove this link.

I did merge some pull requests recently to skinenigmang.

Can I mark both projects as having an "Active maintainer" on the overview page? This would mean that I will ignore any future Pull Requests on any of those projects.

**Comment by a-mair** [comment]
There are plans to be active here someday, but I don't know, when. So I'd say "no" to "Active maintainer" for the moment. Sorry.

**Comment by M-Reimer** [comment]
Sent invite for "skinenigmang".
I'll keep "extrecmenu" as a "public archive" for now as without maintenance it is better to only have a forward to the actively maintained project, here.
