### ISSUE TITLE
vdr-plugin-vdrmanager

### ISSUE THREAD

**Issue by ghbju** [vdr-projects/vdr-projects.github.io#17]
Hi Manuel,

I'm the creator of the vdrmanager plugin and the associated android app. I would like to continue the further development of this project here on github.

A co-developer has done very much work on this and has also released the android app for the play store, but he was busy the last time. Possibly he also wants access to this project. I could contact him about this.

Best regards,
Bernd

**Comment by M-Reimer** [comment]
I'm sorry that this Issue got lost...
The repo already exists here: https://github.com/vdr-projects/vdr-plugin-vdrmanager/
And currently no one has access to it. Meaning that I have not added any accounts who could push to there.
If you like to continue maintaining on the above Repo, just comment here and I'll send you an invitation to get a maintainer.

**Comment by M-Reimer** [comment]
Still interested in developing vdrmanager? At least for now it is more or less unmaintained.

You also mentioned you want to contact the current "co-maintainer". Any response from him?

Sorry again for my initial late response but so far you didn't respond again and I don't want to have this issue open forever. I'll wait another week and then close here.

**Comment by ghbju** [comment]
Sorry for the delay! Yes - I'm still interested in further developing vdrmanager. And I've contacted my co-developer. He has switched away from Android and so he is currently not doing any work for this project.

**Comment by M-Reimer** [comment]
Sent you an invite

**Comment by M-Reimer** [comment]
Just one more question: Currently "vdrmanager" is listed with "unknown maintainer state" on https://vdr-projects.github.io/
Can I update this to "Active maintainer", now?
