### ISSUE TITLE
softhddevice-drm-gles

### ISSUE THREAD

**Issue by rellla** [vdr-projects/vdr-projects.github.io#19]
Hi,
if you want, you can add https://github.com/rellla/vdr-plugin-softhddevice-drm as `softhddevice-drm-gles` to the plugins list and add myself as an active maintainer. 
Thanks
rellla

**Comment by M-Reimer** [comment]
I can add that of course. Thanks for the information.

Just wondering why you didn't name the repo the same as your plugin? Even the README mentions softhddevice-drm-gles.git.

**Comment by rellla** [comment]
Huh. Maybe i really should do that. This is a leftover from forking it from zillevdr. I was afraid from changing the repo name until now. I will check that and ping you to change the link once i've done it. Would that be ok for you?

**Comment by rellla** [comment]
Done. I've renamed the repository.
