### ISSUE TITLE
Wrong source of vdr-plugin-yaepghd ...

### ISSUE THREAD

**Issue by unf** [vdr-projects/vdr-projects.github.io#2]
vdr-plugin-yaepghd wurde seit 2009 nimmer auf vdr-developer.git gepflegt. Lucian hat 2013 einen Mirror angelegt und etwas weitergepflegt: https://github.com/lucianm/vdr-plugin-yaepghd

**Comment by CReimer** [comment]
Danke. Ist gefixt.
