### ISSUE TITLE
vdr-plugin-iptv

### ISSUE THREAD

**Issue by Zabrimus** [vdr-projects/vdr-projects.github.io#23]
Since the current maintainer don't have a VDR setup anymore. See [rofafor/vdr-plugin-iptv](https://github.com/rofafor/vdr-plugin-iptv/issues/12#issuecomment-2115531103) i want to takeover maintaince.

The currently active developement takes place at
[https://github.com/Zabrimus/vdr-plugin-iptv](https://github.com/Zabrimus/vdr-plugin-iptv)

**Comment by M-Reimer** [comment]
Probably you should enable "Issues" in your fork. This is no requirement but could be useful if users want to report problems.
