### ISSUE TITLE
Please add the Plugin "xmltv4vdr"

### ISSUE THREAD

**Issue by FireFlyVDR** [vdr-projects/vdr-projects.github.io#26]
Project page: https://github.com/FireFlyVDR/vdr-plugin-xmltv4vdr
Documentation: https://github.com/FireFlyVDR/vdr-plugin-xmltv4vdr/blob/main/README

**Comment by M-Reimer** [comment]
If at all possible please create a PR for that.

**Comment by wirbel-at-vdr-portal** [comment]
Hi FireFly,

added to the list.
Closing now as completed.

Please re-open, if neccessary.
