### ISSUE TITLE
XXV

### ISSUE THREAD

**Issue by te36de** [vdr-projects/vdr-projects.github.io#27]
Würde gerne XXV in das vdr-projekts reinstellen. Die 1.6.1 Version läuft bei mir unter gentoo jetzt halbwegs akzeptabel mit wenigen patches. Weiss/glaube nicht, das ich da viel Zeit habe, mehr zu machen, aber ich fand das immer so tolle Software, das es prima wäre, wenn das nicht total verloren geht, und derzeit findet google nur noch eine Stelle wo es liegt.

**Comment by M-Reimer** [comment]
Grundlegende GIT Kenntnisse sind vorhanden?

Ich kann das Repo schon anlegen und gerne auch "vorbestücken". Die Patches will ich aber eigentlich nicht einbauen müssen.

**Comment by te36de** [comment]
Danke!

Bin ich blind... ich dachte bevor ich hier das issue aufgemacht habe gab es https://github.com/vdr-projects/xxv gar nicht mehr oeffentlich zugaenglich ... ? 

Das mit dem git krieg ich schon irgendwie hin. Wenn nicht melde ich mich.

Hatte gedacht das das ganze git verloren sei, hatte deswegen als ich vor zwei wochen angefangen hatte auch kein 1.7.0 gesucht. War zumindestens so wie ich das im gentoo git gesucht hatte nie beim gentoo ins repo reingewandert.

Werde jetzt erst mal gucken ob ich das ganze ebuild auf 1.7.0 umgebaut und zum laufen kriege, macht ja keinen Sinn auf der 1.6.1 weiter zu laufen, wenn man die 1.7.0 auch zum laufen kriegt.

**Comment by te36de** [comment]
Last mich wissen, ob/wann ich das repo editieren kann (derzeit geht es nicht0, ansonsten mache ich halt ein eigenes repo auf und kopiere alles rueber.

**Comment by M-Reimer** [comment]
Richte ich heute Abend ein

**Comment by M-Reimer** [comment]
Hast du eine Einladung bekommen?

**Comment by M-Reimer** [comment]
Do you have access? Can we close here?

**Comment by te36de** [comment]
Yes, works fine. Thanks.
