### ISSUE TITLE
gentoo-overlay bitte ?

### ISSUE THREAD

**Issue by te36de** [vdr-projects/vdr-projects.github.io#28]
Koenntet Ihr bitte ein ein repo "gentoo-overlay" einrichten damit man dort die ebuild directories fuer VDR repos einrichten kann ? Es gibt zwar fuer die meisten VDR projekte schon repos die im offiziellen gentoo portage baum sind, aber da sind die Qualitaetsansprueche so hoch, das das da so fuer portage anfaenger wie mich nicht sinnvoll ist. Ich wuerde halt natuerlich zuerst die xxv ebuilds da reinstellen wollen. Denke aber mal das da uebre die zeit auch andere das gerne nutzen, die gentoo verwenden werden.

**Comment by M-Reimer** [comment]
Im Prinzip: Warum nicht. Meinetwegen als "Zwischenstation". Falls ebuilds offiziell werden können sie ja hier eigentlich raus.

**Comment by te36de** [comment]
Genau.!

Oder man bahaelt nur das -9999 ebuild hier - anscheinend sind die im gentoo repo nicht mehr so haeufig ... nicht gewollt ? Machts auf jeden Fall schwer, bugfixes schnell zum "Kunden" zu bringen, wenn man nicht "einfach" nach /usr/local, ohne gentoo installieren will.

Wahrscheinlich weil vielleicht viele maintainer dort gar keine aktiven projektautoren sind, sondern "bloss" gentoo maintainer....

**Comment by te36de** [comment]
Einmal einrichten bitte ? vdr-projects/gentoo-overlay ... ?! Den Rest kann ich besorgen.

**Comment by M-Reimer** [comment]
Erledigt

**Comment by te36de** [comment]
Danke. Gerade Ferien, wird a weng dauern...
