### ISSUE TITLE
rofafor plugins

### ISSUE THREAD

**Issue by olloESP** [vdr-projects/vdr-projects.github.io#4]
... seem to be actively maintained here:  https://github.com/rofafor - please add mirrors.

**Comment by M-Reimer** [comment]
I hope I've caught them all

**Comment by madmartin** [comment]
Hello @M-Reimer @olloESP 
I found that @rofafor itself states that he has no vdr development setup any more and so will  not continue to maintain his plugins

Source: 

https://github.com/rofafor/vdr-plugin-iptv/issues/12
https://github.com/rofafor/vdr-plugin-iptv/issues/13

Maybe you @M-Reimer as member of the vdr-projects organisation can try to convince rofafor to share his repositories with your organisation?
