### ISSUE TITLE
Some plugins

### ISSUE THREAD

**Issue by ua0lnj** [vdr-projects/vdr-projects.github.io#5]
Dvd
http://sourceforge.net/projects/dvdplugin/
I use it and can give patches for it.

Chanman
Why not working status, I use it. What mean working, with last vdr?

mp3, mplayer
http://www.muempf.de/

weatherng
I have working version of it.

Image
No code in https://github.com/vdr-projects/vdr-plugin-image
Patches https://www.vdr-portal.de/forum/index.php?thread/132196-image-plugin-patch/

**Comment by M-Reimer** [comment]
Thanks for the list.

- Dvd: I could give it a try to migrate the CSV repo over to a new GIT repo in context of the vdr-projects organisation for you to point Pull-Requests to for your patches.
- Chanman: I remember that I had build issues with this at some point. Yes "working" means: Most recent VDR version. If it is not working with this, it is "not working" as the developer did not care to make it work with the latest VDR release. I could create a new repo for this, too, if you are interested in fixing it.
- mp3, mplayer Will be added. Status "maintained", for now, as they seem to build with latest VDR.
- weatherng: Same as for some of the above Plugins: I could set up a repo for this if you want to provide fixes as Pull Request.
- Image: Probably unmaintained, too. I'll set this one up as new repo with the given patches applied.

**Comment by M-Reimer** [comment]
DVD: Done https://github.com/vdr-projects/vdr-plugin-dvd

**Comment by M-Reimer** [comment]
All added now. I decided to also add "mp3/mplayer" for now as there is a patch needed to make it compile which never was added by the author for years.

Feel free to point Pull Requests to the new repos. Until then all Plugins which don't compile with latest VDR will be listed as "not working".

**Comment by M-Reimer** [comment]
Thanks for your contributions. Please give a short comment once all the plugins, you commited to recently, have a status where they are working. As soon as this is the case, I would tag a new release for all of them.

**Comment by M-Reimer** [comment]
If you are interested, I can also add you as Maintainer to all the plugins so you can commit directly and tag releases by yourself. I won't be able to test any of these anyway so it would be best if you, as active user, could decide which state is worth to be tagged as release.

**Comment by ua0lnj** [comment]
While I have time to do vdr, I probably can.

**Comment by M-Reimer** [comment]
Invitations are out. Would be great if you could tag a release for "chanman" at some point. We had this in vdr4arch in the past but had to disable its building. If a new "known stable" release would exist, I could reenable building this plugin.
