### ISSUE TITLE
Logos repo

### ISSUE THREAD

**Issue by fiveten59** [vdr-projects/vdr-projects.github.io#6]
If you're interested in I maintain a logos repo with about 6200 png files used by vdr
The link is https://github.com/fiveten59/Logos
Regards

**Comment by M-Reimer** [comment]
There are competing projects with Logos. Another project, I know of, is:
https://github.com/MegaV0lt/Picons2VDR
which uses Picons as the base to automatically create the Icons.

I don't know where the existing projects differ but I would prefer to only link to one project.

And, at least so far, only VDR plugins are linked. But I'll keep this Issue open for now as a reminder for future steps after all plugins have been properly added.

**Comment by fiveten59** [comment]
Ok Thanks

**Comment by M-Reimer** [comment]
@fiveten59 I finally found time to separate plugins and addons/tools.
But I don't just want to call your project "Logos" (which is all I currently have as a name). Can you upload a README.md to your repo explaining your project a bit (probably also some usage hints and instructions) and give it a proper name?
